### PR TITLE
fix: color asan option

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Comment by Antonov548** [comment]
@krlmlr version of `RDcsan` in the docker which doesn't show warnings related to `DWARF`. `readelf` shows correct debug symbols without warnings. 

---
But in the tests there is still not callstack from `igraph.so`. Wondering if it could be related to the fact that `igraph.so` is not linked to `asan` library.

**Comment by Antonov548** [comment]
@krlmlr I tried set of different options to fix this issue.

Sanitaizer shows this error now: `LLVMSymbolizer: error reading file: No such file or directory`.

Also when it shows call stack, it shows in which library memory leack was detected: `#1 0x7f66aa7f84f6  (/tmp/RtmpGG6vpr/pkgload136bb4f200ded/igraph.so+0x2734f6) (BuildId: 9b573d30c53e43851d040ffb8f6814630743775c)`

I don't know much about this. But have felling that R make `tmp` copy of dynamic library `igraph.so` and load it in the process. At the end of R process Sanitazer makes report and try to symbolize the binary it doesn't exists anymore, R delete it from `tmp`. It's just theory, but I would like to hear your thoughts on this.

---

It's more about from where R takes dynamic library? Why `load_all()` only works for Szabolcs? etc. I will try to move in this direction.

**Comment by krlmlr** [comment]
Not sure, let's discuss on Tuesday.

**Comment by krlmlr** [comment]
Thanks.

I think we now understand the issue regarding the source reference: https://github.com/igraph/rigraph/pull/813#issuecomment-1576015809 .

Regarding the readelf warnings: what is the crucial change? Do we need:

```
export CFLAGS="-g -fno-omit-frame-pointer -Og -gdwarf32 -gdwarf-3"
export CXXFLAGS="-g -fno-omit-frame-pointer -Og -gdwarf32 -gdwarf-3"
```

? Anything else?

**Comment by Antonov548** [comment]
> Regarding the readelf warnings: what is the crucial change? Do we need:

Nice👍 

To remove warning we need to use another version of `dwarf`, since by default it choose `version: 5` to compile `igraph.so`. As I understood 5 is experimental. `-gdwarf-4` also should be fine. I tried it.

**Comment by krlmlr** [comment]
Can you please adapt https://github.com/cynkra/r-debug as needed?

**Comment by krlmlr** [comment]
Please work on the "latest" branch, not "main".

**Comment by Antonov548** [comment]
@krlmlr correct asan option is `color` - https://github.com/google/sanitizers/wiki/SanitizerCommonFlags

**Comment by krlmlr** [comment]
Nice, thanks! Can we base this image on https://github.com/cynkra/r-debug/tree/latest for now?

**Comment by krlmlr** [comment]
Can you please test this locally and then push the change straight to the main branch?

**Pull request merged**
