### PR TITLE
chore: environment variables

### PR DESCRIPTION
**Pull request by Antonov548**
- modify `ASAN_OPTIONS` to check memory leaks
- add `TESTTHAT_PARALLEL=false` for igraph tests

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Should we perhaps set the env vars only after we install all the packages?

**Comment by Antonov548** [comment]
> Should we perhaps set the env vars only after we install all the packages?

For this options seems it doesn't matter. Because installation of packages doesn't overwrite any of them. But if you prefer I can make them after install.

**Comment by krlmlr** [comment]
I thought that the installation might be slower if these options are used.

**Comment by Antonov548** [comment]
> I thought that the installation might be slower if these options are used.

Ah, okay. Make sense. I will try to move them after and run sanitizer.

**Comment by Antonov548** [comment]
@krlmlr it works.

I still can't resolve issue with nice call stack from `igraph.so`. Something wrong with debug symbols after coompilation of `rigraph`. And this docker image and sanitaizer like a black box and it's hard to investigate the root cause.

I wondering if we should try to compile R in docker with same steps in instruction which Szabolcs wrote? 
Because I just don't know in which direction I can move with this issue.

**Comment by krlmlr** [comment]
Setting up a Docker image from scratch sounds good.

I'm experimenting with Colima on macOS (https://github.com/abiosoft/colima), can't even get R to run on that system. A simpler, smaller Docker image built from scratch could help here.

**Pull request merged**
